#!/usr/bin/env python

#
# usage
# 
# githubstealer [name or url]
#
# Then retrieves (clones) all the related github repositories in ./[name]/*
#

from bs4                             import BeautifulSoup
from os.path                         import expanduser
from selenium                        import webdriver
from selenium.webdriver.common.by    import By
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.support.ui   import Select
from selenium.webdriver.support.ui   import WebDriverWait
from selenium.webdriver.support      import expected_conditions as ec
import re
import sys

def get_option(headless):
    options = webdriver.ChromeOptions()
    if headless == True:
        options.add_argument('--headless')
    return options

headless           = "--headless" in sys.argv
driver             = webdriver.Chrome(
                         "./drivers/chromedriver78", # XXX needs to be fixed
                         options=get_option(headless)
                     )
wait               = WebDriverWait(driver, 7)

args = [x for x in sys.argv[1:] if x.startswith('https://github.com/')]

if len(args) == 0:
    print("\nURL required.\n\n")
    sys.exit()

url = re.search('https://[^/]+/[^/]+', args[0])

if not url:
    print("\nURL not found.\n\n")
    sys.exit()

user = url.group(0).replace("https://github.com/", "")
url  = "{}?tab=repositories".format(url.group(0))
driver.get(url)

repos = []

for line in driver.page_source.encode('utf-8').split('\n'):
    match = re.search("/{}/[^/^\"]+".format(user), line)
    if match and (not match.group(0) in repos):
        repos.append(match.group(0))
        print(match.group(0))


